### ISSUE TITLE
Issue with content that is greater than the height of the cell

### ISSUE THREAD

**Issue by artknight** [nadeesha/gridster-bootstrap#8]
![screen shot 2016-02-19 at 9 44 01 am](https://cloud.githubusercontent.com/assets/157762/13178529/5409fdbc-d6ed-11e5-8dad-79015a80651d.png)

The construction of a bootstrap layout should allow for the cell content to grow without overlap with the cells below.

**Comment by nadeesha** [comment]
This is one of the limitations of the algorithm. Unfortunately, the max height of the cell cannot grow beyond what is fed.

I'm deprecating the library because the problem it tries to solve is better solved by [Gridstack](http://troolee.github.io/gridstack.js/).
